version: 0.2
phases:

  install:
    commands:
      - apt-get -qq install hugo

  build:
    commands:
      - hugo -F

  post_build:
    commands:
      - aws s3 sync public s3://josh.sansomsherwill.com
      - aws cloudfront create-invalidation --distribution-id E2XYNIDVJYUFMI --paths "/*" 