version: 0.2
phases:

  pre_build:
    commands:
      - apt-get -qq install hugo

  build:
    commands:
      - hugo

  post_build:
    commands:
      - aws s3 sync public s3://josh.sansomsherwill.com
artifacts:
  files: 
    - public/**/*