baseURL = "https://josh.sansomsherwill.com"
languageCode = "en-us"
title = "Josh Sansom"
theme = "hyde-hyde"

enableEmoji = true


## Site Settings
[params]
    author = "Author"
    title = "Title"
    description = "Some [hopefully interesting] excerpts from my brain."
    authorimage = "img/josh.sansomsherwill.jpg"
    dateformat = "Jan 2, 2006"

    # sidebar, copyright & license
    showBuiltWith = false

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"

## Social Accounts
[params.social]
    github = "sansomguy"
    twitter = "sansomguy"
    stackoverflow = "2267000"
    email = "joshwebd@gmail.com"
    linkedin = "sansomguy"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"